name: HeroChat
main: com.dthielke.herochat.HeroChat
version: 5.0.0
website: http://www.herocraftonline.com
authors: [DThielke]
description: Chat channel system
depend: [Vault]
commands:
  herochat:
    aliases: ['ch']
    description: Root HeroChat command
    usage: /<command>
  msg:
    aliases: ['tell', 'pm']
    description: Private messaging command
    usage: /<command> <player> <message>
  ignore:
    aliases: ['ignore']
    description: Ignores a player
    usage: /<command> <player>